language: objective-c

podfile: Example/Podfile

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail && xcodebuild build test -workspace Example/IMOFilterStack.xcworkspace -scheme IMOFilterStack-Example -configuration Debug -sdk iphonesimulator
  - pod lib lint --quick

